/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import javax.swing.ButtonGroup;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
/**
 *
 * @author senyo
 */
public class dashboard extends javax.swing.JFrame {

        private PDType1Font pdfFont;

    // Candidate Info Model 
class CandidateInfo {
    String indexNumber;
    String name;
    String contact;
    String gender;
    String age;
    String schoolCompleted;
    String yearOfCompletion;
}

// School Choice Model 
class SchoolChoice {
    int choiceNumber;
    String category;
    String program;
    String residence;
        private String schoolCodeName;
    }

// Storage Variables 
private CandidateInfo candidateInfo = new CandidateInfo();
private final List<SchoolChoice> schoolChoices = new ArrayList<>();
private int choiceCounter = 1;   // keep track of 5 choices

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
       pdfFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                 
         ButtonGroup choiceGroup = new ButtonGroup();
         choiceGroup.add(j1stChoiceRadioButton);
         choiceGroup.add(j12ndChoiceRadioButton);
         choiceGroup.add(j3rdChoiceRadioButton);
         choiceGroup.add(j4thChoiceRadioButton);
         choiceGroup.add(j5thChoiceRadioButton);
         
         
         
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        CandidateDetailsBox = new javax.swing.JPanel();
        indexNumberIndicator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        indexNumberIndicatorTextbox = new javax.swing.JTextPane();
        candidateNameIndicator = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        candidateNameIndicatorTextbox = new javax.swing.JTextPane();
        contactInfoindicator = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        contactInfoindicatortextbox = new javax.swing.JTextPane();
        genderID = new javax.swing.JLabel();
        genderIDComboBox = new javax.swing.JComboBox<>();
        ageID = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ageIDTextBox = new javax.swing.JTextPane();
        schCompletedID = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        schCompletedIDTextbox = new javax.swing.JTextPane();
        yearOfComplectionID = new javax.swing.JLabel();
        yearOfComplectionIDComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        schoolSelectionPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        catAID = new javax.swing.JLabel();
        catAIDcomboBox = new javax.swing.JComboBox<>();
        catBID = new javax.swing.JLabel();
        catBIDcomboBox = new javax.swing.JComboBox<>();
        catCID = new javax.swing.JLabel();
        catCIDcomboBox = new javax.swing.JComboBox<>();
        programChoice = new javax.swing.JLabel();
        selectProgram = new javax.swing.JLabel();
        selectProgramComboBox = new javax.swing.JComboBox<>();
        j1stChoiceRadioButton = new javax.swing.JRadioButton();
        j12ndChoiceRadioButton = new javax.swing.JRadioButton();
        j3rdChoiceRadioButton = new javax.swing.JRadioButton();
        j4thChoiceRadioButton = new javax.swing.JRadioButton();
        j5thChoiceRadioButton = new javax.swing.JRadioButton();
        residenceChoice = new javax.swing.JLabel();
        residenceChoiceComboBox = new javax.swing.JComboBox<>();
        addtolistButton = new javax.swing.JButton();
        clearlistButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        saveallButton = new javax.swing.JButton();
        clearallButton = new javax.swing.JButton();
        submitToPrintButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Choice Selection");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(234, 222, 222));

        headerTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        headerTitle.setText("SCHOOL CHOICE SELECTION(SHS ONLY)");

        CandidateDetailsBox.setBackground(new java.awt.Color(234, 222, 222));
        CandidateDetailsBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidate Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        indexNumberIndicator.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        indexNumberIndicator.setForeground(new java.awt.Color(255, 51, 51));
        indexNumberIndicator.setText("INDEX NUMBER:");

        indexNumberIndicatorTextbox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(indexNumberIndicatorTextbox);

        candidateNameIndicator.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        candidateNameIndicator.setForeground(new java.awt.Color(255, 51, 51));
        candidateNameIndicator.setText("CANDIDATE NAME:");

        candidateNameIndicatorTextbox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(candidateNameIndicatorTextbox);

        contactInfoindicator.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactInfoindicator.setForeground(new java.awt.Color(255, 51, 51));
        contactInfoindicator.setText("PARENT/GUARDIAN CONTACT:");

        contactInfoindicatortextbox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(contactInfoindicatortextbox);

        genderID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        genderID.setForeground(new java.awt.Color(255, 51, 51));
        genderID.setText("GENDER:");

        genderIDComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        genderIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        ageID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ageID.setForeground(new java.awt.Color(255, 51, 51));
        ageID.setText("AGE:");

        ageIDTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(ageIDTextBox);

        schCompletedID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        schCompletedID.setForeground(new java.awt.Color(255, 51, 51));
        schCompletedID.setText(" SCHOOL COMPLETED:");

        jScrollPane5.setViewportView(schCompletedIDTextbox);

        yearOfComplectionID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        yearOfComplectionID.setForeground(new java.awt.Color(255, 51, 51));
        yearOfComplectionID.setText("YEAR OF COMPLETION");

        yearOfComplectionIDComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        yearOfComplectionIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993" }));

        saveButton.setBackground(new java.awt.Color(51, 51, 255));
        saveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CandidateDetailsBoxLayout = new javax.swing.GroupLayout(CandidateDetailsBox);
        CandidateDetailsBox.setLayout(CandidateDetailsBoxLayout);
        CandidateDetailsBoxLayout.setHorizontalGroup(
            CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(indexNumberIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addComponent(candidateNameIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(contactInfoindicator, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115)
                .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                                .addComponent(genderID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(ageID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                                .addComponent(schCompletedID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addComponent(yearOfComplectionID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearOfComplectionIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        CandidateDetailsBoxLayout.setVerticalGroup(
            CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderIDComboBox)
                                    .addComponent(ageID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(genderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schCompletedID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearOfComplectionID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearOfComplectionIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandidateDetailsBoxLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandidateDetailsBoxLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(indexNumberIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(candidateNameIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CandidateDetailsBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactInfoindicator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPane7.setBackground(new java.awt.Color(234, 222, 222));
        jTextPane7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextPane7.setForeground(new java.awt.Color(255, 0, 0));
        jTextPane7.setText("MUST CHOOSE FIVE (5) SCHOOLS (1ST - 5TH CHOICE). CANDIDATE MUST SELECT AT LEAST TWO (2) SCHOOLS WITH DAY AS THEIR RESIDENTIAL PREFERENCE.  MAY SELECT FIRST FIVE (5) CHOICES FROM CATEGORY C, CANNOT CHOOSE MORE THAN TWO (2) SCHOOLS IN CATEGORY B AND  CANNOT CHOOSE MORE THAN ONE (1) SCHOOL IN CATEGORY A.");
        jScrollPane7.setViewportView(jTextPane7);

        schoolSelectionPanel.setBackground(new java.awt.Color(234, 222, 222));
        schoolSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("ACTIVATE CHOICE TO SELECT CATEGORY");

        jPanel4.setBackground(new java.awt.Color(234, 222, 222));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("PUBLIC SCHOOLS( 1 CHOICE, 1 CAT, 1 PROGRAM AT EACH SELECTION)");

        catAID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        catAID.setForeground(new java.awt.Color(0, 0, 204));
        catAID.setText("CAT A:");

        catAIDcomboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        catAIDcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0010101 - Achimota School  ", "0010102 - Accra Academy  ", "0010106 - Presbyterian Boys' Secondary School, Legon  ", "0010401 - Wesley Grammar School  ", "0010701 - St. Thomas Aquinas Senior High School  ", "0010801 - Accra Girls' Senior High School  ", "0011001 - St. Mary's Senior High School  ", "0020101 - Koforidua Senior High Technical School  ", "0020102 - Pope John Senior High & Minor Seminary  ", "0020104 - Ghana Senior High School, Koforidua  ", "0020301 - Aburi Girls' Senior High School  ", "0020402 - Okuapemman School  ", "0020701 - St. Peter's Senior High School, Nkwatia  ", "0030101 - St. Augustine's College  ", "0030102 - Adisadel College  ", "0030103 - Holy Child School  ", "0030104 - Mfantsipim School  ", "0030107 - Wesley Girls' High School  ", "0030201 - Ghana National College  ", "0030301 - Mfantsiman Girls' Secondary School  ", "0040101 - Archbishop Porter Girls' Secondary School  ", "0040102 - St. John's School, Sekondi  ", "0040104 - Ghana Secondary Technical School, Takoradi  ", "0040105 - Fijai Senior High School  ", "0050102 - St. Louis Senior High School  ", "0050104 - T.I. Ahmadiyya Senior High School, Kumasi  ", "0050108 - Prempeh College  ", "0050110 - Opoku Ware School  ", "0050111 - Kumasi High School  ", "0050201 - Yaa Asantewaa Girls' Senior High School  ", "0050501 - St. Monica's Senior High School, Mampong  ", "0060104 - Sunyani Senior High School  ", "0060106 - St. James Seminary Senior High School  ", "0070101 - Mawuli School  ", "0070102 - Keta Senior High Technical School  ", "0070105 - Bishop Herman College  ", "0070106 - OLA Senior High School, Ho  ", "0080101 - Tamale Senior High School  ", "0090101 - Navrongo Senior High School  ", "0090102 - Bolgatanga Senior High School  ", "0090505 - Notre Dame Seminary Senior High School  ", "0100101 - Wa Senior High School  ", "0100102 - St. Francis Xavier Junior Seminary  ", "0100401 - Lawra Senior High School  ", "0100701 - Wa Senior High Technical School  " }));

        catBID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        catBID.setForeground(new java.awt.Color(0, 0, 204));
        catBID.setText("CAT B:");

        catBIDcomboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        catBIDcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0021301 - Abuakwa State College  ", "0010103 - Accra High School  ", "0050112 - Adanwomase Senior High School  ", "0030202 - Aggrey Memorial A.M.E. Zion Senior High School  ", "0051601 - Agogo State College  ", "0130101 - Ahafoman Senior High School  ", "0040103 - Ahantaman Girls' Senior High School  ", "0020501 - Akim Oda Senior High School  ", "0020502 - Akim Swedru Senior High School  ", "0050105 - Anglican Senior High School, Kumasi  ", "0070301 - Anlo Senior High School  ", "0030401 - Apam Senior High School  ", "0050103 - Armed Forces Senior High Technical School  ", "0020601 - Asamankese Senior High School  ", "0031001 - Assin Manso Senior High School  ", "0090301 - Bawku Senior High School  ", "0130201 - Bechem Presbyterian Senior High School  ", "0051101 - Bekwai SDA Senior High School  ", "0020401 - Benkum Senior High School  ", "0060301 - Berekum Senior High School  ", "0110201 - Bibiani Senior High Technical School  ", "0080301 - Bimbilla Senior High School  ", "0090103 - Bolgatanga Girls' Senior High School  ", "0030601 - Breman Asikuma Senior High School  ", "0010502 - Chemu Senior High School  ", "0080201 - Dagbon State Senior High Technical School  ", "0140101 - Damongo Senior High School  ", "0060101 - Dormaa Senior High School  ", "0030701 - Edinaman Senior High School  ", "0040301 - Fiaseman Senior High School  ", "0160101 - Gambaga Girls' Senior High School  ", "0011401 - Ghanata Senior High School  ", "0080102 - Ghana Senior High School, Tamale (GHANASCO)  ", "0040501 - Half Assini Senior High School  ", "0070501 - Hohoe E.P. Senior High School  ", "0100201 - Jirapa Senior High School  ", "0100501 - Kaleo Senior High Technical School  ", "0010108 - Kinbu Senior High Technical School  ", "0050301 - Konongo Odumase Senior High School  ", "0070401 - Kpando Senior High School  ", "0150101 - Krachi Senior High Technical School  ", "0020801 - Krobo Girls' Senior High School  ", "0050101 - Kumasi Academy  ", "0010301 - Labone Senior High School  ", "0020802 - Manya Krobo Senior High School  ", "0070104 - Mawuko Girls' Senior High School  ", "0160201 - Nalerigu Senior High School  ", "0120201 - Nkoranman Senior High School  ", "0070601 - Nkwanta Senior High School  ", "0060402 - Notre Dame Girls' Senior High School  ", "0040401 - Nsein Senior High School  ", "0050401 - Obuasi Senior High Technical School  ", "0010201 - Odorgonno Senior High School  ", "0020103 - Ofori Panin Senior High School  ", "0050601 - Osei Kyeretwie Senior High School (OKESS)  ", "0010107 - Osu Presbyterian Senior High School  ", "0090201 - Sandema Senior High School  ", "0110101 - Sefwi Wiawso Senior High School  ", "0070201 - Sogakope Senior High School  ", "0050502 - St. Joseph Senior High School, Mampong  ", "0010403 - St. John's Grammar Senior High School  ", "0020201 - Suhum Presbyterian Senior High School  ", "0020202 - Suhum Senior High Technical School  ", "0030501 - Swedru Senior High School  ", "0040201 - Tarkwa Senior High School  ", "0120101 - Techiman Senior High School  ", "0010501 - Tema Senior High School  ", "0050801 - Tepa Senior High School  ", "0100301 - Tumu Senior High Technical School  ", "0080103 - Vitting Senior High Technical School  ", "0011101 - West Africa Senior High School  ", "0060201 - Wenchi Methodist Senior High School  ", "0030801 - Winneba Senior High School  ", "0090401 - Zebilla Senior High Technical School  " }));

        catCID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        catCID.setForeground(new java.awt.Color(0, 0, 204));
        catCID.setText("CAT C:");

        catCIDcomboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        catCIDcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0070302 - Abor Senior High School  ", "0030802 - Aburaman Senior High School  ", "0010104 - Accra Wesley Girls' High School  ", "0011201 - Ada Senior High School  ", "0070107 - Adaklu Senior High School  ", "0020901 - Adeiso Presbyterian Senior High School  ", "0050107 - Adventist Senior High School, Kumasi  ", "0050602 - Aduman Senior High School  ", "0050302 - Akrofuom Senior High Technical School  ", "0070502 - Alavanyo Senior High Technical School  ", "0011501 - Amasaman Senior High Technical School  ", "0070402 - Anfoega Senior High School  ", "0050106 - Asanteman Senior High School  ", "0110102 - Asawinso Senior High School  ", "0120102 - Atebubu Senior High School  ", "0021001 - Begoro Presbyterian Senior High School  ", "0110501 - Bodi Senior High School  ", "0140201 - Bole Senior High School  ", "0160301 - Bunkpurugu Senior High Technical School  ", "0090501 - Chiana Senior High School  ", "0050402 - Christ the King Senior High School, Obuasi  ", "0070202 - Dabala Senior High Technical School  ", "0110301 - Dadieso Senior High School  ", "0150301 - Dambai Senior High School  ", "0060302 - Drobo Senior High School  ", "0030901 - Dunkwa Senior High Technical School  ", "0010202 - Ebenezer Senior High School  ", "0050701 - Effiduase Senior High Commercial School  ", "0040402 - Esiama Senior High Technical School  ", "0090202 - Fumbisi Senior High School  ", "0100601 - Funsi Senior High School  ", "0130102 - Goaso Senior High School  ", "0030402 - Gomoa Senior High Technical School  ", "0010109 - Holy Trinity Cathedral Senior High School  ", "0130301 - Hwidiem Senior High School  ", "0100103 - Islamic Senior High School, Wa  ", "0110401 - Juaboso Senior High School  ", "0050901 - Juaso Senior High Technical School  ", "0030602 - Jukwa Senior High School  ", "0080104 - Kalpohin Senior High School  ", "0010402 - Kaneshie Senior High Technical School  ", "0150102 - Kete-Krachi Senior High Technical School  ", "0120301 - Kintampo Senior High School  ", "0030702 - Komenda Senior High Technical School  ", "0021201 - Kwabeng Anglican Senior High Technical School  ", "0100402 - Lambussie Senior High School  ", "0020403 - Larteh-Presec Senior High School  ", "0050802 - Mankranso Senior High School  ", "0020302 - Methodist Girls' Senior High School, Mamfe  ", "0160201 - Nalerigu Senior High School  ", "0020105 - New Juaben Senior High Commercial School  ", "0051201 - New Edubiase Senior High School  ", "0020702 - Nkawkaw Senior High School  ", "0150201 - Nkonya Senior High School  ", "0060501 - Nsawkaw Senior High School  ", "0020203 - Nsawam Senior High School  ", "0010601 - Nungua Senior High School  ", "0030502 - Nyakrom Senior High Technical School  ", "0030106 - Oguaa Senior High Technical School  ", "0070103 - OLA Girls' Senior High School, Kenyasi  ", "0010302 - Osu-Presec Senior High School  ", "0011301 - Prampram Senior High School  ", "0040302 - Prestea Senior High Technical School  ", "0100202 - Queen of Peace Senior High School, Nadowli  ", "0140301 - Salaga Senior High School  ", "0080202 - Savelugu Senior High School  ", "0040106 - Sekondi College  ", "0040202 - St. Augustine's Senior High School, Bogoso  ", "0020503 - St. Francis Senior High Technical School, Akim Swedru  ", "0050202 - St. Mary's Girls' Senior High School, Konongo  ", "0060102 - Sunyani Methodist Senior High Technical School  ", "0080105 - Tamale Islamic Senior High School  ", "0060202 - Techiman-Krobo Senior High School  ", "0090302 - Tempane Senior High School  ", "0010503 - Tema Methodist Day Senior High School  ", "0031101 - Twifo Praso Senior High School  ", "0030105 - University Practice Senior High School  ", "0160102 - Walewale Senior High Technical School  ", "0010111 - Wesley Girls' Senior High School, Accra  ", "0051701 - Wesley High School, Bekwai  ", "0080401 - Wulensi Senior High School  ", "0080501 - Yendi Senior High School  ", "0020803 - Yilo Krobo Senior High School  ", "0090104 - Zuarungu Senior High School  " }));

        programChoice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        programChoice.setForeground(new java.awt.Color(255, 0, 0));
        programChoice.setText("PROGRAM CHOICE");

        selectProgram.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        selectProgram.setForeground(new java.awt.Color(0, 0, 204));
        selectProgram.setText("PRGRAM CODE + NAME:");

        selectProgramComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        selectProgramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101 - Agricultural Science", "201 - Business ", "301 - Technical", "401 - Home Economics ", "402 - Visual Arts ", "501 - General Arts", "502 - General Science" }));

        j1stChoiceRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        j1stChoiceRadioButton.setText("1ST CHOICE");
        j1stChoiceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1stChoiceRadioButtonActionPerformed(evt);
            }
        });

        j12ndChoiceRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        j12ndChoiceRadioButton.setText("2ND CHOICE");

        j3rdChoiceRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        j3rdChoiceRadioButton.setText("3RD CHOICE");

        j4thChoiceRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        j4thChoiceRadioButton.setText("4TH CHOICE");

        j5thChoiceRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        j5thChoiceRadioButton.setText("5TH CHOICE");

        residenceChoice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        residenceChoice.setForeground(new java.awt.Color(255, 0, 0));
        residenceChoice.setText("RESIDENCE CHOICE");

        residenceChoiceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "DAY", "BOARDING" }));

        addtolistButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addtolistButton.setText("ADD");
        addtolistButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addtolistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtolistButtonActionPerformed(evt);
            }
        });

        clearlistButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearlistButton.setText("CLEAR");
        clearlistButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearlistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(j1stChoiceRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j12ndChoiceRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(j3rdChoiceRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(j4thChoiceRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j5thChoiceRadioButton))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(catBID)
                                .addComponent(catAID))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catAIDcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(catBIDcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(catCID)
                                    .addGap(18, 18, 18)
                                    .addComponent(catCIDcomboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(programChoice)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(selectProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(residenceChoice)
                                                .addComponent(addtolistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(selectProgramComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(residenceChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(clearlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(27, 27, 27)))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1stChoiceRadioButton)
                    .addComponent(j12ndChoiceRadioButton)
                    .addComponent(j3rdChoiceRadioButton)
                    .addComponent(j4thChoiceRadioButton)
                    .addComponent(j5thChoiceRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catAID)
                    .addComponent(catAIDcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catBID)
                    .addComponent(catBIDcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catCID)
                    .addComponent(catCIDcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(programChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectProgram)
                    .addComponent(selectProgramComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residenceChoice)
                    .addComponent(residenceChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtolistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout schoolSelectionPanelLayout = new javax.swing.GroupLayout(schoolSelectionPanel);
        schoolSelectionPanel.setLayout(schoolSelectionPanelLayout);
        schoolSelectionPanelLayout.setHorizontalGroup(
            schoolSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolSelectionPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(schoolSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        schoolSelectionPanelLayout.setVerticalGroup(
            schoolSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(234, 222, 222));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        saveallButton.setBackground(new java.awt.Color(0, 0, 255));
        saveallButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveallButton.setForeground(new java.awt.Color(255, 255, 255));
        saveallButton.setText("SAVE ALL");
        saveallButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveallButtonActionPerformed(evt);
            }
        });

        clearallButton.setBackground(new java.awt.Color(255, 51, 51));
        clearallButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearallButton.setForeground(new java.awt.Color(255, 255, 255));
        clearallButton.setText("CLEAR ALL");
        clearallButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearallButtonActionPerformed(evt);
            }
        });

        submitToPrintButton.setBackground(new java.awt.Color(0, 153, 0));
        submitToPrintButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitToPrintButton.setForeground(new java.awt.Color(255, 255, 255));
        submitToPrintButton.setText("SUBMIT");
        submitToPrintButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitToPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitToPrintButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitToPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(saveallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(clearallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(submitToPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CandidateDetailsBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerTitle)
                .addGap(330, 330, 330))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schoolSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CandidateDetailsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(schoolSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearlistButtonActionPerformed
       schoolChoices.clear();
       choiceCounter = 1;
       JOptionPane.showMessageDialog(this, "All school choices cleared! You can start adding again.");  // TODO add your handling code here:
    }//GEN-LAST:event_clearlistButtonActionPerformed

    private void clearallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallButtonActionPerformed
        candidateInfo = new CandidateInfo();
        schoolChoices.clear();
        choiceCounter = 1;

        // Reset UI fields
        indexNumberIndicatorTextbox.setText("");
        candidateNameIndicatorTextbox.setText("");
        contactInfoindicatortextbox.setText("");
        ageIDTextBox.setText("");
        schCompletedIDTextbox.setText("");
        genderIDComboBox.setSelectedIndex(0);
        yearOfComplectionIDComboBox.setSelectedIndex(0);
        catAIDcomboBox.setSelectedIndex(0);
        catBIDcomboBox.setSelectedIndex(0);
        catCIDcomboBox.setSelectedIndex(0);
        selectProgramComboBox.setSelectedIndex(0);
        residenceChoiceComboBox.setSelectedIndex(0);

        JOptionPane.showMessageDialog(this, "All candidate information and school choices cleared!");        // TODO add your handling code here:
    }//GEN-LAST:event_clearallButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    candidateInfo.indexNumber = indexNumberIndicatorTextbox.getText().trim();
    candidateInfo.name = candidateNameIndicatorTextbox.getText().trim();
    candidateInfo.contact = contactInfoindicatortextbox.getText().trim();
    candidateInfo.gender = genderIDComboBox.getSelectedItem().toString();
    candidateInfo.age = ageIDTextBox.getText().trim();
    candidateInfo.schoolCompleted = schCompletedIDTextbox.getText().trim();
    candidateInfo.yearOfCompletion = yearOfComplectionIDComboBox.getSelectedItem().toString();

    JOptionPane.showMessageDialog(this, "Candidate information saved successfully!");        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addtolistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtolistButtonActionPerformed
  if (choiceCounter > 5) {
        JOptionPane.showMessageDialog(this, "You can only add up to 5 choices.");
        return;
    }

    // Determine which category was selected and get the school info
    String selectedCategory = "";
    String schoolCodeName = "";
    
    if (!catAIDcomboBox.getSelectedItem().toString().equals(" ")) {
        selectedCategory = "A";
        schoolCodeName = catAIDcomboBox.getSelectedItem().toString();
    } else if (!catBIDcomboBox.getSelectedItem().toString().equals(" ")) {
        selectedCategory = "B";
        schoolCodeName = catBIDcomboBox.getSelectedItem().toString();
    } else if (!catCIDcomboBox.getSelectedItem().toString().equals(" ")) {
        selectedCategory = "C";
        schoolCodeName = catCIDcomboBox.getSelectedItem().toString();
    } else {
        JOptionPane.showMessageDialog(this, "Please select a school from one of the categories!");
        return;
    }

    // Determine choice number from radio buttons
    int choiceNumber = 0;
    if (j1stChoiceRadioButton.isSelected()) {
        choiceNumber = 1;
    } else if (j12ndChoiceRadioButton.isSelected()) {
        choiceNumber = 2;
    } else if (j3rdChoiceRadioButton.isSelected()) {
        choiceNumber = 3;
    } else if (j4thChoiceRadioButton.isSelected()) {
        choiceNumber = 4;
    } else if (j5thChoiceRadioButton.isSelected()) {
        choiceNumber = 5;
    } else {
        JOptionPane.showMessageDialog(this, "Please select a choice number (1st-5th)!");
        return;
    }

    SchoolChoice sc = new SchoolChoice();
    sc.choiceNumber = choiceNumber;
    sc.category = selectedCategory;
    sc.program = selectProgramComboBox.getSelectedItem().toString();
    sc.residence = residenceChoiceComboBox.getSelectedItem().toString();
    sc.schoolCodeName = schoolCodeName; // Store the school info

    schoolChoices.add(sc);
    choiceCounter++;

    JOptionPane.showMessageDialog(this, "Choice " + sc.choiceNumber + " added successfully!");

    }//GEN-LAST:event_addtolistButtonActionPerformed

    private void saveallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveallButtonActionPerformed
         if (candidateInfo.name == null || candidateInfo.indexNumber == null) {
        JOptionPane.showMessageDialog(this, "Please save candidate information first!");
        return;
    }
    if (schoolChoices.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No school choices added yet!");
        return;
    }

    JOptionPane.showMessageDialog(this, "All candidate data and school choices saved successfully!");
    }//GEN-LAST:event_saveallButtonActionPerformed

    private void submitToPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitToPrintButtonActionPerformed
       if (candidateInfo.name == null || candidateInfo.indexNumber == null) {
        JOptionPane.showMessageDialog(this, "Please save candidate information first!");
        return;
    }
    if (schoolChoices.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No school choices added yet!");
        return;
    }

    String fileName = candidateInfo.name.replace(" ", "_") + "_" 
                    + candidateInfo.indexNumber + ".pdf";
    
    // Show where the file will be saved
    String currentDir = System.getProperty("user.dir");
    JOptionPane.showMessageDialog(this, "PDF will be saved to: " + currentDir + "\\" + fileName);

    try (PDDocument doc = new PDDocument()) {
        PDPage page = new PDPage();
        doc.addPage(page);

        try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
            cs.setFont(pdfFont, 12);
            cs.beginText();
            cs.setLeading(14.5f);
            cs.newLineAtOffset(50, 700);
            
            // Candidate Info
            cs.showText("SCHOOL CHOICE SELECTION FORM"); 
            cs.newLine(); cs.newLine();
            
       
            cs.showText("Candidate Information:"); cs.newLine();
            cs.showText("Index Number: " + candidateInfo.indexNumber); cs.newLine();
            cs.showText("Candidate Name: " + candidateInfo.name); cs.newLine();
            cs.showText("Gender: " + candidateInfo.gender); cs.newLine();
            cs.showText("Age: " + candidateInfo.age); cs.newLine();
            cs.showText("School Completed: " + candidateInfo.schoolCompleted); cs.newLine();
            cs.showText("Year of Completion: " + candidateInfo.yearOfCompletion); cs.newLine();
            cs.showText("Parent/Guardian Contact: " + candidateInfo.contact); cs.newLine();
            cs.newLine();
            
            // School Choices
            cs.showText("School Choices:"); cs.newLine();
            for (SchoolChoice sc : schoolChoices) {
                cs.showText(sc.choiceNumber + getOrdinalSuffix(sc.choiceNumber) + " Choice: " + sc.schoolCodeName);
                cs.newLine();
                cs.showText("   Category: " + sc.category + ", Program: " + sc.program + ", Residence: " + sc.residence);
                cs.newLine(); cs.newLine();
            }
            cs.endText();
        }

        doc.save(new File(fileName));
        JOptionPane.showMessageDialog(this, "PDF generated successfully: " + fileName + "\nLocation: " + new File(fileName).getAbsolutePath());

    } catch (Exception e) {
        // Show detailed error message
        JOptionPane.showMessageDialog(this, 
            "Error while generating PDF: " + e.getMessage() + 
            "\n\nStack Trace: " + java.util.Arrays.toString(e.getStackTrace()),
            "PDF Generation Error", 
            JOptionPane.ERROR_MESSAGE);
           // Also print to console
    }
}

// Add this helper method
private String getOrdinalSuffix(int number) {
    if (number >= 11 && number <= 13) {
        return "th";
    }
            return switch (number % 10) {
                case 1 -> "st";
                case 2 -> "nd";
                case 3 -> "rd";
                default -> "th";
            };
    }//GEN-LAST:event_submitToPrintButtonActionPerformed

    private void j1stChoiceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1stChoiceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1stChoiceRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CandidateDetailsBox;
    private javax.swing.JButton addtolistButton;
    private javax.swing.JLabel ageID;
    private javax.swing.JTextPane ageIDTextBox;
    private javax.swing.JLabel candidateNameIndicator;
    private javax.swing.JTextPane candidateNameIndicatorTextbox;
    private javax.swing.JLabel catAID;
    private javax.swing.JComboBox<String> catAIDcomboBox;
    private javax.swing.JLabel catBID;
    private javax.swing.JComboBox<String> catBIDcomboBox;
    private javax.swing.JLabel catCID;
    private javax.swing.JComboBox<String> catCIDcomboBox;
    private javax.swing.JButton clearallButton;
    private javax.swing.JButton clearlistButton;
    private javax.swing.JLabel contactInfoindicator;
    private javax.swing.JTextPane contactInfoindicatortextbox;
    private javax.swing.JLabel genderID;
    private javax.swing.JComboBox<String> genderIDComboBox;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel indexNumberIndicator;
    private javax.swing.JTextPane indexNumberIndicatorTextbox;
    private javax.swing.JRadioButton j12ndChoiceRadioButton;
    private javax.swing.JRadioButton j1stChoiceRadioButton;
    private javax.swing.JRadioButton j3rdChoiceRadioButton;
    private javax.swing.JRadioButton j4thChoiceRadioButton;
    private javax.swing.JRadioButton j5thChoiceRadioButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JLabel programChoice;
    private javax.swing.JLabel residenceChoice;
    private javax.swing.JComboBox<String> residenceChoiceComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveallButton;
    private javax.swing.JLabel schCompletedID;
    private javax.swing.JTextPane schCompletedIDTextbox;
    private javax.swing.JPanel schoolSelectionPanel;
    private javax.swing.JLabel selectProgram;
    private javax.swing.JComboBox<String> selectProgramComboBox;
    private javax.swing.JButton submitToPrintButton;
    private javax.swing.JLabel yearOfComplectionID;
    private javax.swing.JComboBox<String> yearOfComplectionIDComboBox;
    // End of variables declaration//GEN-END:variables
}
